// Auto-generated by Supabase CLI: npx supabase gen types typescript --project-id <project-id>
// DO NOT EDIT MANUALLY. Re-generate with: pnpm gen:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      api_quota_limits: {
        Row: {
          monthly_limit: number
          resource_type: string
          role_name: string
        }
        Insert: {
          monthly_limit?: number
          resource_type: string
          role_name: string
        }
        Update: {
          monthly_limit?: number
          resource_type?: string
          role_name?: string
        }
        Relationships: []
      }
      api_quota_usage: {
        Row: {
          count: number
          resource_type: string
          user_id: string
          year_month: string
        }
        Insert: {
          count?: number
          resource_type: string
          user_id: string
          year_month: string
        }
        Update: {
          count?: number
          resource_type?: string
          user_id?: string
          year_month?: string
        }
        Relationships: []
      }
      email_logs: {
        Row: {
          created_at: string | null
          error: string | null
          id: string
          message_id: string | null
          metadata: Json | null
          recipient: string
          sent_by: string | null
          status: string
          subject: string
          type: string
        }
        Insert: {
          created_at?: string | null
          error?: string | null
          id?: string
          message_id?: string | null
          metadata?: Json | null
          recipient: string
          sent_by?: string | null
          status?: string
          subject: string
          type: string
        }
        Update: {
          created_at?: string | null
          error?: string | null
          id?: string
          message_id?: string | null
          metadata?: Json | null
          recipient?: string
          sent_by?: string | null
          status?: string
          subject?: string
          type?: string
        }
        Relationships: []
      }
      export_usage: {
        Row: {
          count: number
          export_type: string
          user_id: string
          year_month: string
        }
        Insert: {
          count?: number
          export_type: string
          user_id: string
          year_month: string
        }
        Update: {
          count?: number
          export_type?: string
          user_id?: string
          year_month?: string
        }
        Relationships: []
      }
      feature_suggestions: {
        Row: {
          admin_notes: string | null
          created_at: string | null
          description: string
          id: string
          importance: string
          notify_on_release: boolean
          status: string
          suggestion_type: string
          target_platform: string
          title: string
          updated_at: string | null
          user_email: string
          user_id: string
          user_name: string | null
        }
        Insert: {
          admin_notes?: string | null
          created_at?: string | null
          description: string
          id?: string
          importance?: string
          notify_on_release?: boolean
          status?: string
          suggestion_type: string
          target_platform?: string
          title: string
          updated_at?: string | null
          user_email: string
          user_id: string
          user_name?: string | null
        }
        Update: {
          admin_notes?: string | null
          created_at?: string | null
          description?: string
          id?: string
          importance?: string
          notify_on_release?: boolean
          status?: string
          suggestion_type?: string
          target_platform?: string
          title?: string
          updated_at?: string | null
          user_email?: string
          user_id?: string
          user_name?: string | null
        }
        Relationships: []
      }
      group_invitations: {
        Row: {
          created_at: string
          email: string
          expires_at: string
          group_id: string
          id: string
          invited_by: string
          status: string
        }
        Insert: {
          created_at?: string
          email: string
          expires_at?: string
          group_id: string
          id?: string
          invited_by: string
          status?: string
        }
        Update: {
          created_at?: string
          email?: string
          expires_at?: string
          group_id?: string
          id?: string
          invited_by?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_invitations_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_members: {
        Row: {
          created_at: string
          group_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          group_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          group_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_shares: {
        Row: {
          admin_comment: string | null
          created_at: string
          date_from: string
          date_to: string
          due_date: string | null
          entries: Json
          entry_count: number
          group_id: string
          id: string
          note: string | null
          period_type: string
          project_ids: string[] | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          submitted_at: string | null
          tag_ids: string[] | null
          total_hours: number
          user_id: string
        }
        Insert: {
          admin_comment?: string | null
          created_at?: string
          date_from: string
          date_to: string
          due_date?: string | null
          entries?: Json
          entry_count?: number
          group_id: string
          id?: string
          note?: string | null
          period_type: string
          project_ids?: string[] | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          submitted_at?: string | null
          tag_ids?: string[] | null
          total_hours?: number
          user_id: string
        }
        Update: {
          admin_comment?: string | null
          created_at?: string
          date_from?: string
          date_to?: string
          due_date?: string | null
          entries?: Json
          entry_count?: number
          group_id?: string
          id?: string
          note?: string | null
          period_type?: string
          project_ids?: string[] | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          submitted_at?: string | null
          tag_ids?: string[] | null
          total_hours?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_shares_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_sharing_settings: {
        Row: {
          created_at: string
          group_id: string
          shared_project_ids: string[] | null
          sharing_enabled: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          group_id: string
          shared_project_ids?: string[] | null
          sharing_enabled?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          group_id?: string
          shared_project_ids?: string[] | null
          sharing_enabled?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_sharing_settings_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          created_at: string
          id: string
          join_code: string | null
          max_members: number
          name: string
          owner_id: string
          share_deadline_day: number | null
          share_frequency: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          join_code?: string | null
          max_members?: number
          name: string
          owner_id: string
          share_deadline_day?: number | null
          share_frequency?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          join_code?: string | null
          max_members?: number
          name?: string
          owner_id?: string
          share_deadline_day?: number | null
          share_frequency?: string | null
        }
        Relationships: []
      }
      plan_roles: {
        Row: {
          plan: string
          role_name: string
        }
        Insert: {
          plan: string
          role_name: string
        }
        Update: {
          plan?: string
          role_name?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          email: string
          id: string
          role: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email: string
          id: string
          role?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email?: string
          id?: string
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          archived: boolean
          color: string
          created_at: number
          default_tag_id: string | null
          deleted_at: string | null
          earnings_enabled: boolean
          hourly_rate: number | null
          id: string
          is_default: boolean
          name: string
          sort_order: number | null
          target_hours: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          archived?: boolean
          color: string
          created_at: number
          default_tag_id?: string | null
          deleted_at?: string | null
          earnings_enabled?: boolean
          hourly_rate?: number | null
          id: string
          is_default?: boolean
          name: string
          sort_order?: number | null
          target_hours?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          archived?: boolean
          color?: string
          created_at?: number
          default_tag_id?: string | null
          deleted_at?: string | null
          earnings_enabled?: boolean
          hourly_rate?: number | null
          id?: string
          is_default?: boolean
          name?: string
          sort_order?: number | null
          target_hours?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      promo_codes: {
        Row: {
          active: boolean
          code: string
          created_at: string
          created_by: string | null
          current_uses: number
          discount_pct: number
          id: string
          max_uses: number | null
          plan: string
          valid_from: string
          valid_until: string | null
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          created_by?: string | null
          current_uses?: number
          discount_pct: number
          id?: string
          max_uses?: number | null
          plan?: string
          valid_from?: string
          valid_until?: string | null
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          created_by?: string | null
          current_uses?: number
          discount_pct?: number
          id?: string
          max_uses?: number | null
          plan?: string
          valid_from?: string
          valid_until?: string | null
        }
        Relationships: []
      }
      promo_redemptions: {
        Row: {
          id: string
          promo_code_id: string
          redeemed_at: string
          user_id: string
        }
        Insert: {
          id?: string
          promo_code_id: string
          redeemed_at?: string
          user_id: string
        }
        Update: {
          id?: string
          promo_code_id?: string
          redeemed_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "promo_redemptions_promo_code_id_fkey"
            columns: ["promo_code_id"]
            isOneToOne: false
            referencedRelation: "promo_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "promo_redemptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      role_export_limits: {
        Row: {
          export_type: string
          monthly_limit: number
          role_name: string
        }
        Insert: {
          export_type: string
          monthly_limit: number
          role_name: string
        }
        Update: {
          export_type?: string
          monthly_limit?: number
          role_name?: string
        }
        Relationships: []
      }
      stripe_events: {
        Row: {
          event_id: string
          event_type: string
          processed_at: string
        }
        Insert: {
          event_id: string
          event_type: string
          processed_at?: string
        }
        Update: {
          event_id?: string
          event_type?: string
          processed_at?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean | null
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          granted_by: string | null
          group_id: string | null
          id: string
          plan: string
          promo_code_id: string | null
          status: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          granted_by?: string | null
          group_id?: string | null
          id?: string
          plan?: string
          promo_code_id?: string | null
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          granted_by?: string | null
          group_id?: string | null
          id?: string
          plan?: string
          promo_code_id?: string | null
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_promo_code_id_fkey"
            columns: ["promo_code_id"]
            isOneToOne: false
            referencedRelation: "promo_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          admin_notes: string | null
          created_at: string | null
          description: string
          id: string
          issue_time: string | null
          issue_type: string
          platform: string
          priority: string
          resolved_at: string | null
          resolved_by: string | null
          status: string
          subject: string
          updated_at: string | null
          user_email: string
          user_id: string
          user_name: string | null
        }
        Insert: {
          admin_notes?: string | null
          created_at?: string | null
          description: string
          id?: string
          issue_time?: string | null
          issue_type: string
          platform?: string
          priority?: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          subject: string
          updated_at?: string | null
          user_email: string
          user_id: string
          user_name?: string | null
        }
        Update: {
          admin_notes?: string | null
          created_at?: string | null
          description?: string
          id?: string
          issue_time?: string | null
          issue_type?: string
          platform?: string
          priority?: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          subject?: string
          updated_at?: string | null
          user_email?: string
          user_id?: string
          user_name?: string | null
        }
        Relationships: []
      }
      sync_cursors: {
        Row: {
          created_at: string
          device_id: string
          id: string
          last_sync: string
          user_id: string
        }
        Insert: {
          created_at?: string
          device_id: string
          id?: string
          last_sync: string
          user_id: string
        }
        Update: {
          created_at?: string
          device_id?: string
          id?: string
          last_sync?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sync_cursors_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          color: string
          created_at: string
          deleted_at: string | null
          earnings_enabled: boolean
          hourly_rate: number | null
          id: string
          is_default: boolean
          name: string
          sort_order: number | null
          updated_at: string
          user_id: string
        }
        Insert: {
          color?: string
          created_at?: string
          deleted_at?: string | null
          earnings_enabled?: boolean
          hourly_rate?: number | null
          id: string
          is_default?: boolean
          name: string
          sort_order?: number | null
          updated_at?: string
          user_id: string
        }
        Update: {
          color?: string
          created_at?: string
          deleted_at?: string | null
          earnings_enabled?: boolean
          hourly_rate?: number | null
          id?: string
          is_default?: boolean
          name?: string
          sort_order?: number | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tags_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      time_entries: {
        Row: {
          created_at: string
          date: string
          deleted_at: string | null
          description: string
          duration: number
          end_time: number
          id: string
          link: string | null
          project_id: string | null
          start_time: number
          tags: string[] | null
          task_id: string | null
          type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          date: string
          deleted_at?: string | null
          description?: string
          duration: number
          end_time: number
          id: string
          link?: string | null
          project_id?: string | null
          start_time: number
          tags?: string[] | null
          task_id?: string | null
          type: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          date?: string
          deleted_at?: string | null
          description?: string
          duration?: number
          end_time?: number
          id?: string
          link?: string | null
          project_id?: string | null
          start_time?: number
          tags?: string[] | null
          task_id?: string | null
          type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "time_entries_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "time_entries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_settings: {
        Row: {
          currency: string
          daily_target: number | null
          default_hourly_rate: number | null
          entry_save_time: number | null
          floating_timer_auto: boolean
          idle_timeout: number
          language: string
          min_billable_minutes: number
          notifications: boolean
          pomodoro_config: Json
          reminder: Json | null
          theme: string
          updated_at: string
          user_id: string
          week_start_day: number
          weekly_target: number | null
          working_days: number
        }
        Insert: {
          currency?: string
          daily_target?: number | null
          default_hourly_rate?: number | null
          entry_save_time?: number | null
          floating_timer_auto?: boolean
          idle_timeout?: number
          language?: string
          min_billable_minutes?: number
          notifications?: boolean
          pomodoro_config?: Json
          reminder?: Json | null
          theme?: string
          updated_at?: string
          user_id: string
          week_start_day?: number
          weekly_target?: number | null
          working_days?: number
        }
        Update: {
          currency?: string
          daily_target?: number | null
          default_hourly_rate?: number | null
          entry_save_time?: number | null
          floating_timer_auto?: boolean
          idle_timeout?: number
          language?: string
          min_billable_minutes?: number
          notifications?: boolean
          pomodoro_config?: Json
          reminder?: Json | null
          theme?: string
          updated_at?: string
          user_id?: string
          week_start_day?: number
          weekly_target?: number | null
          working_days?: number
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_stats: {
        Row: {
          active_days: number | null
          last_active_date: string | null
          total_entries: number | null
          total_hours: number | null
          total_projects: number | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          active_days?: number | null
          last_active_date?: string | null
          total_entries?: number | null
          total_hours?: number | null
          total_projects?: number | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          active_days?: number | null
          last_active_date?: string | null
          total_entries?: number | null
          total_hours?: number | null
          total_projects?: number | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      webhook_logs: {
        Row: {
          created_at: string
          duration_ms: number | null
          error_message: string | null
          event_id: string
          event_type: string
          id: number
          status: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          duration_ms?: number | null
          error_message?: string | null
          event_id: string
          event_type: string
          id?: number
          status?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          duration_ms?: number | null
          error_message?: string | null
          event_id?: string
          event_type?: string
          id?: number
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      whitelisted_domains: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          domain: string
          id: string
          notes: string | null
          plan: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          domain: string
          id?: string
          notes?: string | null
          plan?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          domain?: string
          id?: string
          notes?: string | null
          plan?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_get_groups: { Args: never; Returns: Json }
      admin_update_group: {
        Args: { p_group_id: string; p_max_members: number }
        Returns: Json
      }
      check_api_quota: {
        Args: {
          p_resource_type: string
          p_user_id: string
          p_year_month: string
        }
        Returns: Json
      }
      check_domain_whitelist: {
        Args: { user_email: string }
        Returns: {
          domain: string
          plan: string
        }[]
      }
      create_group_atomic: {
        Args: { p_name: string; p_owner_id: string }
        Returns: Json
      }
      get_active_users: { Args: { period: string }; Returns: number }
      get_admin_overview: { Args: never; Returns: Json }
      get_all_api_quota_limits: { Args: never; Returns: Json }
      get_daily_email_counts: {
        Args: { p_days?: number }
        Returns: {
          day: string
          failed: number
          sent: number
        }[]
      }
      get_dashboard_bootstrap_data: {
        Args: { p_user_id: string; p_week_from: string; p_week_to: string }
        Returns: Json
      }
      get_domain_stats: { Args: never; Returns: Json }
      get_earnings_report:
        | {
            Args: {
              p_date_from?: string
              p_date_to?: string
              p_user_id: string
            }
            Returns: Json
          }
        | {
            Args: {
              p_date_from?: string
              p_date_to?: string
              p_group_by?: string
              p_user_id: string
            }
            Returns: Json
          }
      get_email_count_by_type: {
        Args: never
        Returns: {
          count: number
          type: string
        }[]
      }
      get_entry_type_breakdown: {
        Args: never
        Returns: {
          entry_count: number
          entry_type: string
          total_hours: number
        }[]
      }
      get_group_analytics: {
        Args: {
          p_date_from?: string
          p_date_to?: string
          p_group_id: string
          p_user_id: string
        }
        Returns: Json
      }
      get_group_member_entries: {
        Args: {
          p_admin_id: string
          p_date_from?: string
          p_date_to?: string
          p_group_id: string
          p_member_id: string
        }
        Returns: Json
      }
      get_group_members_summary: {
        Args: { p_admin_id: string; p_group_id: string }
        Returns: Json
      }
      get_platform_stats: { Args: never; Returns: Json }
      get_premium_breakdown: { Args: never; Returns: Json }
      get_promo_stats: { Args: never; Returns: Json }
      get_today_total_duration: {
        Args: { p_date: string; p_user_id: string }
        Returns: number
      }
      get_top_users: {
        Args: { lim?: number }
        Returns: {
          email: string
          total_hours: number
          user_id: string
        }[]
      }
      get_user_analytics:
        | {
            Args: {
              p_date_from?: string
              p_date_to?: string
              p_user_id: string
            }
            Returns: Json
          }
        | {
            Args: {
              p_date_from?: string
              p_date_to?: string
              p_timezone?: string
              p_user_id: string
            }
            Returns: Json
          }
      get_user_api_quotas: {
        Args: { p_user_id: string; p_year_month: string }
        Returns: Json
      }
      get_user_export_quota: {
        Args: { p_user_id: string; p_year_month: string }
        Returns: Json
      }
      get_user_export_role: { Args: { p_user_id: string }; Returns: string }
      get_user_growth: {
        Args: { weeks?: number }
        Returns: {
          signup_count: number
          week_start: string
        }[]
      }
      get_user_own_stats: { Args: { p_user_id: string }; Returns: Json }
      has_changes_since: {
        Args: { p_since: string; p_user_id: string }
        Returns: boolean
      }
      is_premium: { Args: { check_user_id: string }; Returns: boolean }
      redeem_promo: {
        Args: { p_code: string; p_user_id: string }
        Returns: Json
      }
      track_export_usage: {
        Args: { p_export_type: string; p_user_id: string; p_year_month: string }
        Returns: Json
      }
      upsert_api_quota_limit: {
        Args: {
          p_monthly_limit: number
          p_resource_type: string
          p_role_name: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
