// Supabase database row types — mirror of the SQL schema.
// Used by both the Chrome Extension (src/) and the companion website (web/).
//
// The Database type is auto-generated by the Supabase CLI (see shared/database.types.ts).
// The Db* interfaces below provide semantic union types for use throughout the codebase.
export { type Database } from './database.types'

export interface DbProfile {
  id: string                  // UUID — matches auth.users.id
  email: string
  display_name: string | null
  avatar_url: string | null
  role: 'user' | 'admin'
  created_at: string          // TIMESTAMPTZ ISO string
  updated_at: string
}

export interface DbSubscription {
  id: string
  user_id: string
  stripe_customer_id: string | null
  stripe_subscription_id: string | null
  plan: 'free' | 'premium_monthly' | 'premium_yearly' | 'allin_monthly' | 'allin_yearly' | 'team_10_monthly' | 'team_10_yearly' | 'team_20_monthly' | 'team_20_yearly'
  status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'unpaid' | 'incomplete' | 'expired'
  current_period_start: string | null
  current_period_end: string | null
  cancel_at_period_end: boolean
  granted_by: 'stripe' | 'domain' | 'promo' | 'admin_manual' | null
  promo_code_id: string | null
  group_id: string | null
  created_at: string
  updated_at: string
}

export interface DbProject {
  id: string                  // nanoid — matches local Project.id
  user_id: string
  name: string
  color: string               // Hex color
  target_hours: number | null
  hourly_rate: number | null
  earnings_enabled: boolean
  archived: boolean
  is_default: boolean
  default_tag_id: string | null  // Linked default tag
  sort_order: number | null
  created_at: number          // Unix ms timestamp — matches local Project.createdAt
  updated_at: string          // TIMESTAMPTZ for sync cursor comparison
  deleted_at: string | null   // Soft delete
}

export interface DbTag {
  id: string
  user_id: string
  name: string
  color: string               // Hex color, default '#6366F1'
  hourly_rate: number | null   // Per-tag rate, null = use default
  earnings_enabled: boolean    // Whether included in earnings
  is_default: boolean
  sort_order: number | null
  created_at: string
  updated_at: string
  deleted_at: string | null
}

export interface DbTimeEntry {
  id: string                  // nanoid — matches local TimeEntry.id
  user_id: string
  date: string                // YYYY-MM-DD
  start_time: number          // Unix ms
  end_time: number            // Unix ms
  duration: number            // ms
  project_id: string | null
  task_id: string | null
  description: string
  type: 'manual' | 'stopwatch' | 'pomodoro'
  tags: string[]
  link: string | null
  created_at: string
  updated_at: string
  deleted_at: string | null
}

export interface DbUserSettings {
  user_id: string
  working_days: number
  week_start_day: 0 | 1
  idle_timeout: number
  theme: string
  language: string
  notifications: boolean
  daily_target: number | null
  weekly_target: number | null
  pomodoro_config: {
    workMinutes: number
    shortBreakMinutes: number
    longBreakMinutes: number
    sessionsBeforeLongBreak: number
    soundEnabled: boolean
  }
  default_hourly_rate: number | null
  currency: string
  min_billable_minutes: number
  floating_timer_auto: boolean
  reminder: {
    enabled: boolean
    dayOfWeek: number
    hour: number
    minute: number
  }
  entry_save_time: number
  updated_at: string
}

export interface DbSyncCursor {
  id: string
  user_id: string
  device_id: string
  last_sync: string           // TIMESTAMPTZ ISO string
  created_at: string
}

export interface DbPromoCode {
  id: string
  code: string
  discount_pct: number
  plan: 'premium_monthly' | 'premium_yearly' | 'allin_monthly' | 'allin_yearly' | 'team_10_monthly' | 'team_10_yearly' | 'team_20_monthly' | 'team_20_yearly'
  max_uses: number | null
  current_uses: number
  valid_from: string
  valid_until: string | null
  active: boolean
  created_at: string
  created_by: string | null
}

export interface DbPromoRedemption {
  id: string
  promo_code_id: string
  user_id: string
  redeemed_at: string
}

export interface DbUserStats {
  user_id: string
  total_hours: number
  total_entries: number
  total_projects: number
  active_days: number
  last_active_date: string | null
  updated_at: string
}

export interface DbWhitelistedDomain {
  id: string
  domain: string
  plan: 'premium_monthly' | 'premium_yearly' | 'allin_monthly' | 'allin_yearly' | 'team_10_monthly' | 'team_10_yearly' | 'team_20_monthly' | 'team_20_yearly'
  notes: string | null
  active: boolean
  created_at: string
  created_by: string | null
}

export interface DbGroup {
  id: string
  name: string
  owner_id: string
  join_code: string | null
  max_members: number
  created_at: string
  share_frequency: 'daily' | 'weekly' | 'monthly' | null
  share_deadline_day: number | null
}

export interface DbGroupMember {
  group_id: string
  user_id: string
  role: 'admin' | 'member'
  created_at: string
}

export interface DbGroupInvitation {
  id: string
  group_id: string
  email: string
  invited_by: string
  status: 'pending' | 'accepted' | 'declined' | 'expired'
  created_at: string
  expires_at: string
}

export interface DbGroupSharingSettings {
  group_id: string
  user_id: string
  sharing_enabled: boolean
  shared_project_ids: string[] | null
  created_at: string
  updated_at: string
}

export interface DbGroupShare {
  id: string
  group_id: string
  user_id: string
  period_type: 'day' | 'week' | 'month'
  date_from: string
  date_to: string
  project_ids: string[] | null
  tag_ids: string[] | null
  entry_count: number
  total_hours: number
  entries: unknown  // JSONB snapshot
  note: string | null
  created_at: string
  status: 'open' | 'submitted' | 'approved' | 'denied'
  admin_comment: string | null
  submitted_at: string | null
  reviewed_at: string | null
  reviewed_by: string | null
  due_date: string | null
}

export interface DbSupportTicket {
  id: string
  user_id: string
  user_email: string
  user_name: string | null
  issue_type: 'bug' | 'account' | 'billing' | 'sync' | 'performance' | 'other'
  subject: string
  description: string
  priority: 'low' | 'medium' | 'high' | 'urgent'
  platform: 'chrome_extension' | 'web_app' | 'both'
  issue_time: string | null
  status: 'open' | 'in_progress' | 'resolved' | 'closed'
  admin_notes: string | null
  resolved_at: string | null
  resolved_by: string | null
  created_at: string
  updated_at: string
}

export interface DbFeatureSuggestion {
  id: string
  user_id: string
  user_email: string
  user_name: string | null
  suggestion_type: 'feature' | 'improvement' | 'integration' | 'ui_ux' | 'other'
  title: string
  description: string
  importance: 'nice_to_have' | 'important' | 'critical'
  target_platform: 'chrome_extension' | 'web_app' | 'both'
  notify_on_release: boolean
  status: 'new' | 'under_review' | 'planned' | 'in_progress' | 'implemented' | 'declined'
  admin_notes: string | null
  created_at: string
  updated_at: string
}

// --- Export Quota System ---

export type ExportRole = 'free' | 'pro' | 'team'

export type ExportType = 'pdf' | 'excel' | 'csv'

export interface ExportQuotaItem {
  export_type: ExportType
  limit: number
  used: number
  remaining: number
}

export interface ExportQuota {
  role: ExportRole
  year_month: string  // 'YYYY-MM' UTC
  items: ExportQuotaItem[]
}

export interface TrackExportResult {
  allowed: boolean
  used: number
  limit: number
  error?: string
}

export interface DbPlanRole {
  plan: DbSubscription['plan']
  role_name: ExportRole
}

export interface DbRoleExportLimit {
  role_name: ExportRole
  export_type: ExportType
  monthly_limit: number
}

export interface DbExportUsage {
  user_id: string
  export_type: ExportType
  year_month: string
  count: number
}

export interface DbEmailLog {
  id: string
  recipient: string
  type: string
  subject: string
  status: string
  message_id: string | null
  error: string | null
  metadata: Record<string, unknown>
  created_at: string
  sent_by: string | null
}

