export { sendEmail } from './send'
export type { EmailType } from './send'
export { buildWelcomeEmail } from './templates/welcome'
export { buildGroupInvitationEmail } from './templates/groupInvitation'
export { buildPasswordResetConfirmationEmail } from './templates/passwordResetConfirmation'
export { buildEmailVerificationEmail } from './templates/emailVerification'
export { buildBillingNotificationEmail } from './templates/billingNotification'
export { buildInvoiceReceiptEmail } from './templates/invoiceReceipt'
export { buildTrialEndingEmail } from './templates/trialEnding'
export { buildPasswordResetEmail } from './templates/passwordReset'
export { buildMagicLinkEmail } from './templates/magicLink'
